- name: Copy X11 Script
  template:
    src: x11.sh.j2
    dest: /usr/local/bin/x11
    mode: 0555
  when: helper_x11_copy_script|bool

- name: Copy Tmux Script
  template:
    src: tmux-session.sh.j2
    dest: /usr/local/bin/tmux-session
    mode: 0555
  when: helper_tmux_copy_script|bool

- name: Copy gpg-session Script
  template:
    src: gpg-session.sh.j2
    dest: /usr/local/bin/gpg-session
    mode: 0555
  when:
    - helper_wsl_npiperelay_path != 'none'
    - helper_windows_gpg_agent_path != 'none'

- name: Copy gpg-remote Script
  template:
    src: gpg-remote.sh.j2
    dest: /usr/local/bin/gpg-remote
    mode: 0555
  when:
    - helper_gpg_local_agent != 'none'
    - helper_gpg_remote_agent != 'none'
