- name: Install Common Drivers
  include_role:
    name: pkg-install
  vars:
    pkg_name:
    - mesa
    pkg_apt_name:
    - mesa-utils

- name: Install Nvidia Drivers
  include_role:
    name: pkg-install
  vars:
    pkg_name:
    - xf86-video-nouveau
    pkg_apt_name:
    - xserver-xorg-video-nouveau
  when: linux_graphics_install_nvidia_drivers|bool

- name: Add nouveau to mkinitcpio
  lineinfile:
    path: /etc/mkinitcpio.conf
    regexp: '^MODULES='
    line: MODULES=(nouveau)
  notify:
  - regen mkinitcpio (Arch)
  - regen mkinitcpio (Ubuntu)
  when:
  - linux_graphics_install_nvidia_drivers|bool
  - ansible_distribution in pacman_distros

- name: Install Intel Drivers
  include_role:
    name: pkg-install
  vars:
    pkg_name:
    - xf86-video-intel
    pkg_apt_name:
    - xserver-xorg-video-intel
  when: linux_graphics_install_intel_drivers|bool
