proxy-dns: true
proxy-dns-port: 5054
proxy-dns-upstream:
 - https://dns.quad9.net/dns-query
#  - https://1.1.1.1/dns-query
#  - https://1.0.0.1/dns-query
#  - https://9.9.9.9/dns-query
#  - https://149.112.112.112/dns-query
#  - https://2620:fe::fe/dns-query
#  - https://2620:fe::fe:9/dns-query
