- name: Install Docker
  include_role:
    name: pkg-install
  vars:
    pkg_name:
    - docker
    - docker-compose
  when: dev_utils_install_docker|bool

- name: Create Docker System Config Dirs
  file:
    path: "{{ item }}"
    state: directory
    recurse: true
  with_items:
    - /etc/docker
    - /etc/systemd/system/docker.service.d/
  when: dev_utils_install_docker|bool

- name: Copy docker config
  copy:
    src: "{{ dev_utils_docker_config }}"
    dest: /etc/docker/daemon.json
  notify: restart docker
  when:
  - dev_utils_install_docker|bool
  - dev_utils_docker_config != 'none'

- name: Copy docker configs
  template:
    src: docker.conf.j2
    dest: /etc/systemd/system/docker.service.d/override.conf
  notify: restart docker
  when:
  - dev_utils_install_docker|bool
  - dev_utils_extra_docker_host != 'none'

- name: Add user to docker Group
  user:
    name: "{{ dev_utils_docker_user }}"
    groups: docker
  when:
  - dev_utils_install_docker|bool
  - dev_utils_docker_user != 'none'

- name: Install nodejs
  include_role:
    name: pkg-install
  vars:
    pkg_name:
    - nodejs
    - npm
  when: dev_utils_setup_nodejs|bool

- name: Install kubernetes
  include_role:
    name: pkg-install
  vars:
    pkg_name:
    - kubernetes
    - stern
    pkg_aur_name:
    - kubernetes
    - stern-bin
  when: dev_utils_setup_k8s|bool

- name: Install gcloud
  include_role:
    name: pkg-install
  vars:
    pkg_name:
    - google-cloud-sdk
    pkg_aur_name:
    - google-cloud-sdk
  when: dev_utils_setup_gcloud|bool
