- name: Install KDE
  include_role:
    name: pkg-install
  vars:
    pkg_name:
    - networkmanager
    - nm-connection-editor

- name: systemd Enable Network Manager
  systemd:
    name: "{{ item }}"
    daemon_reload: true
    enabled: true
    state: started
  with_items:
  - NetworkManager
