- name: regen mkinitcpio
  command: mkinitcpio -p linux
  when: ansible_distribution in pacman_distros

- name: regen mkinitcpio
  command: update-initramfs -u
  when: ansible_distribution in apt_distros
