helper_x11_copy_script: false
helper_x11_enable_forwarding: false
helper_host_aliases:
helper_gpg_copy_script: false
helper_wsl_npiperelay_path: none
helper_windows_gpg_agent_path: none
helper_tmux_copy_script: false
