- name: Install Gnome
  include_role:
    name: pkg-install
  vars:
    pkg_name:
    - xorg
    - gnome
    - gnome-extras
    - ttf-dejavu
    - ttf-liberation

# - name: Make User Dirs
#   file:
#     path: "{{ item }}"
#     state: directory
#     recurse: true
#     owner: "{{ linux_desktop_user }}"
#     group: "{{ linux_desktop_user }}"
#   with_items:
#     - ~{{ linux_desktop_user }}/.config
#     - ~{{ linux_desktop_user }}/.local/share/konsole

# - name: Copy User Configs
#   template:
#     src: "{{ item.src }}"
#     dest: "{{ item.dest }}"
#     owner: "{{ linux_desktop_user }}"
#     group: "{{ linux_desktop_user }}"
#   with_items:
#     - { src: konsole/profile.profile, dest: "~{{ linux_desktop_user }}/.local/share/konsole/Profile 1.profile" }
#     - { src: konsole/rc, dest: "~{{ linux_desktop_user }}/.config/konsolerc" }
