# Install multiple packages
# Install a package that must be installed via AUR on Arch
- name: Install Dev Tools
  include_role:
    name: pkg-install
  vars:
    pkg_name:
    - google-cloud-sdk
    - stern
    pkg_aur_name:
    - google-cloud-sdk
    - stern-bin

# Install a common package that is the same across all systems
- name: Install Vim
  include_role:
    name: pkg-install
  vars:
    pkg_name:
    - vim
