- name: Create {{ item.domain }} nginx Log Folder
  file:
    name: /var/log/nginx/{{ item.domain }}
    state: directory

- name: Copy {{ item.domain }} nginx Conf
  template:
    src: proxy.conf.j2
    dest: /etc/nginx/domains/{{ item.domain }}.conf
  when: not (item.custom | default(False))
  notify: restart nginx

- name: Copy Custom {{ item.domain }} nginx Conf
  copy:
    src: "{{ item.custom_file }}"
    dest: /etc/nginx/domains/{{ item.domain }}.conf
  when: (item.custom | default(False))
  notify: restart nginx
