- name: Grub OR Plymouth theme set
  assert:
    that: (personalize_grub_theme != 'none' and personalize_plymouth_theme == 'none') or (personalize_grub_theme == 'none' and personalize_plymouth_theme != 'none')
    msg: 'Cannot set both a Grub and Plymouth theme'
  when: personalize_grub_theme != 'none' or personalize_plymouth_theme != 'none'

- name: Copy Grub Theme
  copy:
    src: "{{ personalize_grub_theme }}"
    dest: /boot/grub/themes/user-theme
  when: personalize_grub_theme != 'none'
  notify: regen grub

- name: Enable Grub Theme
  lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_THEME='
    line: GRUB_THEME=/boot/grub/themes/user-theme/theme.txt
  when: personalize_grub_theme != 'none'
  notify: regen grub

- name: Disable Grub Theme
  lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_THEME='
    line: '# GRUB_THEME=/boot/grub/themes/user-theme/theme.txt'
  when: personalize_plymouth_theme != 'none'
  notify: regen grub

- name: Copy Plymouth Theme
  copy:
    src: "{{ personalize_plymouth_theme }}"
    dest: /usr/share/plymouth/themes/user-theme
  when: personalize_plymouth_theme != 'none'
  notify: regen mkinitcpio

- name: Enable Plymouth Theme
  template:
    src: plymouthd.conf.j2
    dest: /etc/plymouth/plymouthd.conf
  when: personalize_plymouth_theme != 'none'
  notify: regen mkinitcpio
