linux_desktop_display_manager: sddm
linux_desktop_network: networkmanager
linux_desktop_environments:
- kde
linux_desktop_supported_environments:
- none
- gnome
- kde
linux_desktop_supported_display_managers:
- none
- gdm
- sddm
linux_desktop_supported_networks:
- none
- networkmanager
