- name: Validate Cloud Providers
  assert:
    that: not item or item in cloud_supported_providers
    msg: 'Supported Shell types: {{ cloud_supported_providers }}'
  with_items: "{{ cloud_providers }}"

- name: Set local variables
  set_fact:
    cloud_configure_onedrive: "{{ cloud_onedrive_sync_list and cloud_onedrive_sync_list != 'none' }}"

- name: Configure Users
  include: onedrive.yml
  when: cloud_configure_onedrive|bool
