- name: Validate Desktop Environments
  assert:
    that: not item or item in linux_desktop_supported_environments
    msg: 'Supported Shell types: {{ linux_desktop_supported_environments }}'
  with_items: "{{ linux_desktop_environments }}"

- name: Validate Display Manager
  assert:
    that: item in linux_desktop_supported_display_managers
    msg: 'Supported Shell types: {{ linux_desktop_supported_display_managers }}'
  with_items: "{{ linux_desktop_display_manager }}"

- set_fact:
    linux_desktop_install_kde: "{{ linux_desktop_environments and 'kde' in linux_desktop_environments }}"

- name: Install SDDM
  include_role:
    name: linux-desktop-sddm
  when: linux_desktop_display_manager == 'sddm'

- name: Install KDE
  include_role:
    name: linux-desktop-kde
  when: linux_desktop_install_kde|bool
