- name: Validate Display Manager
  assert:
    that: item in linux_desktop_supported_display_managers
    msg: 'Supported Display Manangers: {{ linux_desktop_supported_display_managers }}'
  with_items: "{{ linux_desktop_display_manager }}"

- name: Validate Network Manager
  assert:
    that: item in linux_desktop_supported_networks
    msg: 'Supported Network Managers: {{ linux_desktop_supported_networks }}'
  with_items: "{{ linux_desktop_network }}"

- name: Validate Desktop Environments
  assert:
    that: not item or item in linux_desktop_supported_environments
    msg: 'Supported Desktop Environments: {{ linux_desktop_supported_environments }}'
  with_items: "{{ linux_desktop_environments }}"

- set_fact:
    linux_desktop_install_kde: "{{ linux_desktop_environments and 'kde' in linux_desktop_environments }}"
    linux_desktop_install_gnome: "{{ linux_desktop_environments and 'gnome' in linux_desktop_environments }}"

- name: Install SDDM
  include_role:
    name: linux-desktop-sddm
  when: linux_desktop_display_manager == 'sddm'

- name: Install GDM
  include_role:
    name: linux-desktop-gdm
  when: linux_desktop_display_manager == 'gdm'

- name: Install Network Manager
  include_role:
    name: linux-destop-networkmanager
  when: linux_desktop_network == 'networkmanager'

- name: Install KDE
  include_role:
    name: linux-desktop-kde
  when: linux_desktop_install_kde|bool

- name: Install Gnome
  include_role:
    name: linux-desktop-gnome
  when: linux_desktop_install_gnome|bool
