- name: Install GDM
  include_role:
    name: pkg-install
  vars:
    pkg_name:
    - gdm
    pkg_apt_name:
    - gdm3

- name: systemd Enable GDM
  systemd:
    name: "{{ item }}"
    daemon_reload: true
    enabled: true
    state: started
  with_items:
  - gdm
