- name: Install SDDM
  include_role:
    name: pkg-install
  vars:
    pkg_name:
    - sddm
    - sddm-kcm
    pkg_apt_name:
    - sddm

- name: Configure SDDM (Arch)
  include: display-managers/sddm-arch.yml
  when: ansible_distribution in pacman_distros
