- name: Install GDM
  include_role:
    name: pkg-install
  vars:
    pkg_name:
    - gdm
    pkg_apt_name:
    - gdm3

- name: systemd Enable GDM
  systemd:
    name: "{{ item }}"
    daemon_reload: true
    enabled: true
    state: started
  with_items:
  - gdm

# - name: Make System Dirs
#   file:
#     path: "{{ item }}"
#     state: directory
#     recurse: true
#   with_items:
#     - /etc/sddm.conf.d/

# - name: Copy System Configs
#   template:
#     src: "{{ item.src }}"
#     dest: "{{ item.dest }}"
#   with_items:
#     - { src: hide_aur.conf, dest: /etc/sddm.conf.d/hide_aur.conf }
